import Head from "next/head";
import Table from "@/components/Table";
import { useState } from "react";
import axios from "axios";

const Application = ({ data: initialData }) => {
  const [data, setData] = useState(initialData);
  console.log(initialData);
  return (
    <>
      <Head>
        <title>Applications</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <Table
          headers={["Id", "Name", "Status", "Image", "Ports", "Created At"]}
          rows={data}
          setdata={setData}
        />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const data = await axios.get("http://localhost:5000/api/listcontainers");

  return {
    props: { heading: "Applications ", data: data.data },
  };
};

export default Application;
