import Head from "next/head";
import axios from "axios";
import Table from "@/components/Table";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal"],
});

const Application = () => {
  return (
    <>
      <Head>
        <title>Applications</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Table />
      </main>
    </>
  );
};

export default Application;
