import React, { useState } from "react";
import Head from "next/head";
import ContainerForImageAndVolume from "@/components/ContainerForImageAndVolume";
import { useRouter } from "next/navigation";
import axios from "axios";

const Volumes = ({ initialData }) => {
  const type = "volume";
  const [isChecked, setIsChecked] = useState(new Set());
  const [data, setData] = useState(initialData);
  const { push } = useRouter();

  const refreshHandler = async () => {
    try {
      const data = await axios.get(`http://localhost:5000/api/list${type}s`);

      if (data.status === 200) {
        const initialData = [];
        for (var ele of data.data.Volumes) {
          const obj = {
            col1: ele.Mountpoint,
            col2: ele.Name,
            col3: ele.Driver,
            col4: ele.CreatedAt,
          };

          initialData.push(obj);
        }
        setData(initialData);
      }
    } catch (error) {
      const { status: statusCode } = error.response;
      if (+statusCode === 503) {
        push("/503");
      }
    }
  };

  const deleteObj = async () => {
    try {
      const data = await axios.post(`http://localhost:5000/api/delete${type}`, {
        volumeName: Array.from(isChecked),
      });

      if (data.status === 200) {
        const initialData = [];
        for (var ele of data.data.Volumes) {
          const obj = {
            col2: ele.Name,
            col1: ele.Mountpoint,
            col3: ele.Driver,
            col4: ele.CreatedAt,
          };

          initialData.push(obj);
        }
        setIsChecked(new Set());
        setData(initialData);
      }
    } catch (error) {
      const { status: statusCode } = error.response;
      if (+statusCode === 503) {
        push("/503");
      }
    }
  };

  return (
    <>
      <Head>
        <title>Volumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <ContainerForImageAndVolume
          type={type}
          headers={["Select", "Mount point", "Name", "Driver", "Created"]}
          rows={data}
          setData={setData}
          deleteObj={deleteObj}
          isChecked={isChecked}
          setIsChecked={setIsChecked}
          refreshHandler={refreshHandler}
        />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  try {
    const data = await axios.get("http://localhost:5000/api/listvolumes");

    const initialData = [];
    if (data.status === 200) {
      for (var ele of data.data.Volumes) {
        const obj = {
          col1: ele.Name,
          col2: ele.Mountpoint,
          col3: ele.Driver,
          col4: ele.CreatedAt,
        };

        initialData.push(obj);
      }

      return {
        props: { initialData },
      };
    }
  } catch (error) {
    const { status: statusCode } = error.response;
    if (+statusCode === 503) {
      return {
        redirect: {
          destination: "/503",
          statusCode: 307,
        },
      };
    }
  }
};

export default Volumes;
