import React, { useState } from "react";
import Head from "next/head";
import ContainerForImageAndVolume from "@/components/ContainerForImageAndVolume";
import axios from "axios";

const Volumes = ({ initialData }) => {
  const type = "volume";
  const [isChecked, setIsChecked] = useState(new Set());
  const [data, setData] = useState(initialData);

  const refreshHandler = async () => {
    const data = await axios.get(`http://localhost:5000/api/list${type}s`);

    if (data.status === 200) {
      const initialData = [];
      for (var ele of data.data.Volumes) {
        const obj = {
          col1: ele.Name,
          col2: ele.Mountpoint,
          col3: ele.Driver,
          col4: ele.CreatedAt,
        };

        initialData.push(obj);
      }
      setData(initialData);
    }
  };

  const deleteObj = async () => {
    const data = await axios.post(`http://localhost:5000/api/delete${type}`, {
      volumeName: Array.from(isChecked),
    });

    if (data.status === 200) {
      const initialData = [];
      for (var ele of data.data.Volumes) {
        const obj = {
          col1: ele.Name,
          col2: ele.Mountpoint,
          col3: ele.Driver,
          col4: ele.CreatedAt,
        };

        initialData.push(obj);
      }
      setIsChecked(new Set());
      setData(initialData);
    }
  };

  return (
    <>
      <Head>
        <title>Volumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <ContainerForImageAndVolume
          type={type}
          headers={["Select", "Name", "Mount point", "Driver", "Created"]}
          rows={data}
          setData={setData}
          deleteObj={deleteObj}
          isChecked={isChecked}
          setIsChecked={setIsChecked}
          refreshHandler={refreshHandler}
        />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const data = await axios.get("http://localhost:5000/api/listvolumes");

  const initialData = [];
  if (data.status === 200) {
    for (var ele of data.data.Volumes) {
      const obj = {
        col1: ele.Name,
        col2: ele.Mountpoint,
        col3: ele.Driver,
        col4: ele.CreatedAt,
      };

      initialData.push(obj);
    }
  }

  return {
    props: { heading: "Volumes", initialData },
  };
};

export default Volumes;
