import Head from "next/head";
import axios from "axios";
import { Poppins } from "@next/font/google";
import Layout from "@/Sections/Layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal"],
});

const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`text-red-500 ${poppins.className}`}>
        <Layout>DashBoard</Layout>
      </main>
    </>
  );
};

// export const getServerSideProps = async (ctx) => {
//   const { data } = await axios.get("http://localhost:3000/api/createcontainer");

//   console.log(data);

//   return {
//     props: { data: data },
//   };
// };

export default Home;
