import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import Container from "@/components/Container";

const Application = ({ initialData }) => {
  const [data, setData] = useState(initialData);
  return (
    <>
      <Head>
        <title>Containers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <Container
          headers={[
            "Select",
            "Name",
            "Id",
            "Status",
            "Image",
            "Ports",
            "Created At",
          ]}
          rows={data}
          setData={setData}
        />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const data = await axios.get("http://localhost:5000/api/listcontainers");

  const initialData = [];
  if (data.status === 200) {
    for (var ele of data.data) {
      const obj = {
        col1: ele.Names[0],
        col2: ele.Id,
        col3: ele.State,
        col4: ele.Image,
        col5: ele.Ports.length === 0 ? "-" : ele.Ports[0].PrivatePort,
        col6: ele.Created,
      };

      initialData.push(obj);
    }
  }

  return {
    props: { heading: "Containers ", initialData },
  };
};

export default Application;
