import Row from "@/components/Row";
import Head from "next/head";
import { VscRefresh as RefreshIcon } from "react-icons/vsc";

const Containers = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <Row />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  return {
    props: { heading: "Containers" },
  };
};

export default Containers;
