import React, { useState } from "react";
import Head from "next/head";
import ContainerForImageAndVolume from "@/components/ContainerForImageAndVolume";
import axios from "axios";

const Images = ({ data: initialData }) => {
  const type = "image";
  const [data, setData] = useState(initialData);
  const [isChecked, setIsChecked] = useState(new Set());

  const deleteObj = async () => {
    const data = await axios.post(`http://localhost:5000/api/delete${type}`, {
      image: Array.from(isChecked),
    });

    if (data.status === 200) {
      const initialData = [];
      for (var ele of data.data) {
        const obj = {
          col1: ele.RepoTags[0],
          col2: ele.Id,
          col3: ele.Created,
        };

        initialData.push(obj);
      }

      setData(initialData);
      setIsChecked(new Set());
    }
  };

  const refreshHandler = async () => {
    const data = await axios.get(`http://localhost:5000/api/list${type}s`);

    if (data.status === 200) {
      const initialData = [];
      for (var ele of data.data) {
        const obj = {
          col1: ele.RepoTags[0],
          col2: ele.Id,
          col3: ele.Created,
        };

        initialData.push(obj);
      }

      setData(initialData);
    }
  };

  return (
    <>
      <Head>
        <title>Images</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
      </Head>
      <main>
        <ContainerForImageAndVolume
          type={type}
          headers={["Select", "Tag", "Id", "Created"]}
          rows={data}
          setData={setData}
          deleteObj={deleteObj}
          isChecked={isChecked}
          setIsChecked={setIsChecked}
          refreshHandler={refreshHandler}
        />
      </main>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const data = await axios.get("http://localhost:5000/api/listimages");

  const initialData = [];
  if (data.status === 200) {
    for (var ele of data.data) {
      const obj = {
        col1: ele.RepoTags[0],
        col2: ele.Id,
        col3: ele.Created,
      };

      initialData.push(obj);
    }
  }

  return {
    props: { heading: "Images", data: initialData },
  };
};

export default Images;
